Add friends likes
Mellerh/java-filmorate pull request #3
Opened 2024-09-21 09:03 UTC by Mellerh

2024-09-21 17:48 UTC, EugeneLenkevich requested changes
Привет, Тарас! Спасибо за PR.

Эта работа хороша тем что на ней можно хорошо проработать такой момент как распределение обязанностей по слоям
 У каждого слоя есть свои обязанности, если простыми словами то вот так
- контроллеры маршрутизируют сами запросы на наши сервисы
- сервисы оперируют понятиями предметной области, в них и содержится вся бизнес-логика 
- хранилище же занимается вопросами хранения, фильтрации и выборки данных

Официальное объяснение такое

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2024-09-21 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserServiceIml userService) {
Тут вся фишка в том чтобы передавать именно интерфейс, а не конкретную реализацию. Можно на самом деле вообще без интерфейса обойтись, но раз он у нас есть то давай указывать именно интерфейс, а не конкретную реализацию 
Смысл этого в том, что мы сможем заменять разные реализации вообще без пересборки, а при запуске приложения в зависимости от параметров запуска :)

2024-09-21 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/filmService/FilmServiceIml.java
> +        return filmLikesMap.entrySet().stream()
А вот тут в сервис мы вытаскиваем данные из хранилища и сортируем их в сервисе, однако выборка и сортировка - это обязанности хранилища, потому лучше опять таки спрятать это выражение в метод хранилища. Так же, потом, нам проще будет делать оптимизации хранения данных, прозрачно для сервисов

2024-09-21 17:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/userService/UserServiceIml.java
> +        return inMemoryUserStorage.getAllUserFriendsIds(id).stream()
Вот опять таки, выборка и фильтрация данных, это обязанность хранилища

2024-09-21 18:50 UTC, Mellerh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserServiceIml userService) {
А можно какой-нибудь пример с параметром запуска? Как это в реальных проектах работает

2024-09-21 19:08 UTC, Mellerh commented on src/main/java/ru/yandex/practicum/filmorate/service/filmService/FilmServiceIml.java
> +        return filmLikesMap.entrySet().stream()
Окей. А все проверки на null типа Film film = filmStorage.getFilmById(filmId); и выбрасывания исключения остаётся в сервисах?

2024-09-21 19:09 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserServiceIml userService) {
Вместо реализации попробуй подставить интерфейс, скорее всего сразу заработает

![image](https://github.com/user-attachments/assets/342d39e4-5077-4805-902a-517ee5515bf4)

2024-09-21 19:13 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/filmService/FilmServiceIml.java
> +        return filmLikesMap.entrySet().stream()
Надо исходить из нашей бизнес-логики
Если критическая ситуация (кончились деньги на счету, например) есть в бизнес-процессе, то точно в сервисе
Хотя можно все исключения из сервиса кидать. Если речь про проверяемые конечно же, непроверяемые кидаются где угодно

2024-09-21 19:18 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/filmService/FilmServiceIml.java
> +        return filmLikesMap.entrySet().stream()
А на счет выборки и сортировки в хранилище -это станет хорошо видно в момент когда мы будет прикручивать базу данных, эти операции мы будем делать часто одним запросом

2024-09-21 19:22 UTC, Mellerh commented on src/main/java/ru/yandex/practicum/filmorate/service/filmService/FilmServiceIml.java
> +        return filmLikesMap.entrySet().stream()
А я вот наоборот думал, что по SRP мы в хранилище только лишь храним данные, а всю работу с ними производим в сервисе.
Но, видимо, при подключении Баз данных, хранилище и должно уже с этими данными работать

2024-09-22 03:55 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/filmService/FilmServiceIml.java
> +        return filmLikesMap.entrySet().stream()
Ну, работа с данными - это понятие такое, растяжимое, и сортировка - "работа с данными" и построение отчета продаж - "работа с данными" 
SRP вообще, очень абстрактный и довольно неоднозначный принцип и часто на практике на 100% не работает в чистом виде. Потому и предлагают в данной архитектуре подходить со стороны слоев
Но, на разных проектах бывает и по другому :)

2024-09-22 03:56 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-09-22 10:37 UTC, merged